version: '3.4'

services:
  workflowtemplates:
    image: workflowtemplates
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
