name: Docker Image CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      docker_registry:
            description: 'Registry URL'     
            required: true
            default: 'docker.io/username'
      image_name:
            description: 'Name you wish to use on the docker image (ex. myapp). This will be tagged with :latest, and the git sha'     
            required: true
            default: 'app'
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
      with:
        egress-policy: audit

    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ github.event.inputs.docker_registry }}/${{ github.event.inputs.image_name }}:latest --tag ${{ github.event.inputs.docker_registry }}/${{ github.event.inputs.image_name }}:${{ github.sha }}
    - name: Docker Login
      uses: docker/login-action@adb73476b6e06caddec5db0bc1deacbec8cdd947 # v1.6.0
      with:
        registry: ${{ github.event.inputs.docker_registry }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: true
    - name: Push the Docker image to ${{ github.event.inputs.docker_registry }}
      run: docker push ${{ github.event.inputs.docker_registry }}/${{ github.event.inputs.image_name }}
    - name: Push the Docker image to ${{ github.event.inputs.docker_registry }}
      run: docker push ${{ github.event.inputs.docker_registry }}/${{ github.event.inputs.image_name }}:${{ github.sha }}
